name: Build Sphinx Docs

on:
  push:
    branches:
      - main  # Replace with your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Build docs
      run: |
        cd docs  # Replace with the path to your Sphinx docs
        make html
